import type { AdvisoryEngagement } from "@/types";

/**
 * Selected Advisory Engagements. This spans government work, enterprise
 * advisory engagements and standalone strategic programmes — `track`
 * distinguishes them within one collection and one template at
 * /selected-advisory-engagements/[slug]. Adding the next engagement,
 * of any track, is a data-only change.
 */
export const advisoryEngagements: AdvisoryEngagement[] = [
  {
    slug: "government-digital-governance-programme",
    title: "[Engagement Title Placeholder — Government Digital Governance]",
    track: "Government",
    domainSlugs: ["government-digital-governance"],
    sector: "Government / Public Sector",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: true,
  },
  {
    slug: "ai-governance-operating-model",
    title: "[Engagement Title Placeholder — AI Governance]",
    track: "Enterprise Advisory",
    domainSlugs: ["ai-governance"],
    sector: "Technology",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: true,
  },
  {
    slug: "technology-risk-assurance",
    title: "[Engagement Title Placeholder — Technology Risk]",
    track: "Enterprise Advisory",
    domainSlugs: ["technology-risk"],
    sector: "Financial Services",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: true,
  },
  {
    slug: "third-party-governance-framework",
    title: "[Engagement Title Placeholder — Third Party Governance]",
    track: "Enterprise Advisory",
    domainSlugs: ["third-party-governance"],
    sector: "Healthcare",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: false,
  },
  {
    slug: "dpdp-governance-readiness-programme",
    title: "[Engagement Title Placeholder — DPDP Governance]",
    track: "Strategic Programme",
    domainSlugs: ["dpdp-governance-readiness"],
    sector: "Enterprise Leadership",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: false,
  },
  {
    slug: "ens-readiness-assessment",
    title: "[Engagement Title Placeholder — ENS Readiness]",
    track: "Government",
    domainSlugs: ["cyber-governance"],
    sector: "Government / Public Sector",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: false,
  },
  {
    slug: "pci-dss-advisory",
    title: "[Engagement Title Placeholder — PCI DSS]",
    track: "Enterprise Advisory",
    domainSlugs: ["cyber-governance"],
    sector: "Financial Services",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: false,
  },
  {
    slug: "enterprise-governance-transformation-programme",
    title: "[Engagement Title Placeholder — Enterprise Governance Transformation]",
    track: "Strategic Programme",
    domainSlugs: ["governance-transformation"],
    sector: "Enterprise Leadership",
    engagementType: "[Engagement Type Placeholder]",
    year: "[Year Placeholder]",
    summary: "[Engagement Summary Placeholder]",
    context: "[Engagement Context Placeholder]",
    approach: ["[Approach Step Placeholder 1]", "[Approach Step Placeholder 2]", "[Approach Step Placeholder 3]"],
    outcome: "[Engagement Outcome Placeholder]",
    featured: true,
  },
];

export function getAdvisoryEngagementBySlug(slug: string) {
  return advisoryEngagements.find((engagement) => engagement.slug === slug);
}
