import type { GovernanceDomain } from "@/types";

/**
 * The full governance domain capability map — thirteen domains across
 * four clusters, all live as full pages from launch. Some pages are
 * intentionally concise at first (see `overview`/`focusAreas`); the
 * page and route already exist so publishing more depth later never
 * requires a navigation or routing change.
 *
 * To add a fourteenth domain: append an entry with an existing
 * `cluster` id. To introduce a fifth cluster, add it to
 * governance-clusters.ts first.
 */
export const governanceDomains: GovernanceDomain[] = [
  // ---- Emerging Technology Governance ----
  {
    slug: "ai-governance",
    name: "AI Governance",
    shortName: "AI Governance",
    cluster: "emerging-technology-governance",
    eyebrow: "Governance Domain",
    summary: "[AI Governance — One-Line Summary Placeholder]",
    overview: "[AI Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]", "[Focus Area Placeholder 3]"],
    whoItsFor: ["[Audience Placeholder — CIO]", "[Audience Placeholder — CISO]", "[Audience Placeholder — Board]"],
    relatedEngagementSlugs: ["ai-governance-operating-model"],
    relatedInsightSlugs: ["ai-governance-board-oversight", "judgment-over-frameworks"],
    relatedResourceSlugs: ["ai-governance-maturity-framework", "ai-governance-decision-playbook"],
    featured: true,
  },
  {
    slug: "responsible-ai",
    name: "Responsible AI",
    shortName: "Responsible AI",
    cluster: "emerging-technology-governance",
    eyebrow: "Governance Domain",
    summary: "[Responsible AI — One-Line Summary Placeholder]",
    overview: "[Responsible AI — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — CIO]", "[Audience Placeholder — Chief Risk Officer]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: ["judgment-over-frameworks"],
    relatedResourceSlugs: ["ai-governance-decision-playbook"],
    featured: true,
  },
  {
    slug: "digital-governance",
    name: "Digital Governance",
    shortName: "Digital Governance",
    cluster: "emerging-technology-governance",
    eyebrow: "Governance Domain",
    summary: "[Digital Governance — One-Line Summary Placeholder]",
    overview: "[Digital Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — CIO]", "[Audience Placeholder — Enterprise Leadership]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    relatedResourceSlugs: [],
    featured: false,
  },

  // ---- Risk, Cyber & Assurance ----
  {
    slug: "technology-risk",
    name: "Technology Risk",
    shortName: "Technology Risk",
    cluster: "risk-cyber-assurance",
    eyebrow: "Governance Domain",
    summary: "[Technology Risk — One-Line Summary Placeholder]",
    overview: "[Technology Risk — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]", "[Focus Area Placeholder 3]"],
    whoItsFor: ["[Audience Placeholder — Chief Risk Officer]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: ["technology-risk-assurance"],
    relatedInsightSlugs: ["technology-risk-appetite", "governance-debt"],
    relatedResourceSlugs: ["technology-risk-whitepaper"],
    featured: true,
  },
  {
    slug: "cyber-governance",
    name: "Cyber Governance",
    shortName: "Cyber Governance",
    cluster: "risk-cyber-assurance",
    eyebrow: "Governance Domain",
    summary: "[Cyber Governance — One-Line Summary Placeholder]",
    overview: "[Cyber Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]", "[Focus Area Placeholder 3]"],
    whoItsFor: ["[Audience Placeholder — CISO]", "[Audience Placeholder — Chief Risk Officer]"],
    relatedEngagementSlugs: ["ens-readiness-assessment", "pci-dss-advisory"],
    relatedInsightSlugs: [],
    relatedResourceSlugs: ["cyber-governance-reference-architecture"],
    featured: true,
  },
  {
    slug: "enterprise-risk-governance",
    name: "Enterprise Risk Governance",
    shortName: "Enterprise Risk Governance",
    cluster: "risk-cyber-assurance",
    eyebrow: "Governance Domain",
    summary: "[Enterprise Risk Governance — One-Line Summary Placeholder]",
    overview: "[Enterprise Risk Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Chief Risk Officer]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: ["governance-debt"],
    relatedResourceSlugs: [],
    featured: false,
  },
  {
    slug: "audit-readiness",
    name: "Audit Readiness",
    shortName: "Audit Readiness",
    cluster: "risk-cyber-assurance",
    eyebrow: "Governance Domain",
    summary: "[Audit Readiness — One-Line Summary Placeholder]",
    overview: "[Audit Readiness — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — CISO]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    relatedResourceSlugs: ["audit-readiness-checklist"],
    featured: false,
  },

  // ---- Regulatory, Privacy & Third-Party ----
  {
    slug: "privacy-data-governance",
    name: "Privacy & Data Governance",
    shortName: "Privacy & Data Governance",
    cluster: "regulatory-privacy-third-party",
    eyebrow: "Governance Domain",
    summary: "[Privacy & Data Governance — One-Line Summary Placeholder]",
    overview: "[Privacy & Data Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    relatedResourceSlugs: [],
    featured: false,
  },
  {
    slug: "dpdp-governance-readiness",
    name: "DPDP Governance & Readiness",
    shortName: "DPDP Readiness",
    cluster: "regulatory-privacy-third-party",
    eyebrow: "Governance Domain",
    summary: "[DPDP Governance & Readiness — One-Line Summary Placeholder]",
    overview: "[DPDP Governance & Readiness — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]", "[Focus Area Placeholder 3]"],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — Enterprise Leadership]"],
    relatedEngagementSlugs: ["dpdp-governance-readiness-programme"],
    relatedInsightSlugs: ["dpdp-readiness-priorities"],
    relatedResourceSlugs: ["dpdp-readiness-briefing", "dpdp-compliance-toolkit"],
    featured: true,
  },
  {
    slug: "third-party-governance",
    name: "Third Party Governance",
    shortName: "Third Party Governance",
    cluster: "regulatory-privacy-third-party",
    eyebrow: "Governance Domain",
    summary: "[Third Party Governance — One-Line Summary Placeholder]",
    overview: "[Third Party Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — CISO]"],
    relatedEngagementSlugs: ["third-party-governance-framework"],
    relatedInsightSlugs: ["third-party-risk-in-regulated-sectors", "third-party-accountability-gap"],
    relatedResourceSlugs: ["third-party-risk-assessment-checklist"],
    featured: true,
  },
  {
    slug: "operational-compliance",
    name: "Operational Compliance",
    shortName: "Operational Compliance",
    cluster: "regulatory-privacy-third-party",
    eyebrow: "Governance Domain",
    summary: "[Operational Compliance — One-Line Summary Placeholder]",
    overview: "[Operational Compliance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    relatedResourceSlugs: ["dpdp-compliance-toolkit"],
    featured: false,
  },

  // ---- Public Sector & Transformation ----
  {
    slug: "government-digital-governance",
    name: "Government Digital Governance",
    shortName: "Government Digital Governance",
    cluster: "public-sector-transformation",
    eyebrow: "Governance Domain",
    summary: "[Government Digital Governance — One-Line Summary Placeholder]",
    overview: "[Government Digital Governance — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]", "[Focus Area Placeholder 3]"],
    whoItsFor: ["[Audience Placeholder — Government]", "[Audience Placeholder — Public Sector]"],
    relatedEngagementSlugs: ["government-digital-governance-programme"],
    relatedInsightSlugs: ["government-digital-governance-maturity"],
    relatedResourceSlugs: ["government-digital-governance-artefact-pack"],
    featured: true,
  },
  {
    slug: "governance-transformation",
    name: "Governance Transformation",
    shortName: "Governance Transformation",
    cluster: "public-sector-transformation",
    eyebrow: "Governance Domain",
    summary: "[Governance Transformation — One-Line Summary Placeholder]",
    overview: "[Governance Transformation — Overview Placeholder]",
    focusAreas: ["[Focus Area Placeholder 1]", "[Focus Area Placeholder 2]"],
    whoItsFor: ["[Audience Placeholder — Enterprise Leadership]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: ["enterprise-governance-transformation-programme"],
    relatedInsightSlugs: ["governance-transformation-operating-models", "judgment-over-frameworks"],
    relatedResourceSlugs: ["governance-operating-model-template"],
    featured: false,
  },
];

export function getGovernanceDomainBySlug(slug: string) {
  return governanceDomains.find((domain) => domain.slug === slug);
}

export function getGovernanceDomainsByCluster(clusterId: string) {
  return governanceDomains.filter((domain) => domain.cluster === clusterId);
}
